services:
  rabbitmq:
    image: rabbitmq:management
    env_file: ./.env
    environment:
      RABBITMQ_DEFAULT_USER: $AMQP_USER
      RABBITMQ_DEFAULT_PASS: $AMQP_PASSWORD
    ports:
      - $AMQP_PORT:$AMQP_PORT
      - $AMQP_UI_PORT:$AMQP_UI_PORT
